version: 2

updates:
  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      development-minor-and-patch:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      documentation-tools:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      approved-github-actions:
        patterns:
          - "actions/checkout"
          - "actions/configure-pages"
          - "actions/dependency-review-action"
          - "actions/deploy-pages"
          - "actions/setup-node"
          - "actions/setup-python"
          - "actions/upload-artifact"
          - "actions/upload-pages-artifact"
          - "github/codeql-action"
          - "googleapis/release-please-action"
          - "raven-actions/actionlint"
          - "zizmorcore/zizmor-action"
